"""empty message

Revision ID: 25ebcf64573f
Revises: fd864ad8516d
Create Date: 2024-08-30 18:52:41.456331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ebcf64573f'
down_revision = 'fd864ad8516d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('document_type', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('document_number', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=200), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('role')
        batch_op.drop_column('address')
        batch_op.drop_column('document_number')
        batch_op.drop_column('document_type')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
