"""empty message

Revision ID: b39dec6abf11
Revises: a71d62944a49
Create Date: 2024-09-02 18:36:15.369780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39dec6abf11'
down_revision = 'a71d62944a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('speciality',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('speciality',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
