"""empty message

Revision ID: b84a81b99cc8
Revises: fae1490331e3
Create Date: 2024-09-25 17:42:05.712695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84a81b99cc8'
down_revision = 'fae1490331e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=False))
        batch_op.alter_column('reason_for_appointment',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=250),
               nullable=True)
        batch_op.alter_column('date_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['doctor_id'], ['id'])
        batch_op.drop_column('doctor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('reason_for_appointment',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
